# Generated by Django 6.0.4 on 2026-05-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rute',
            old_name='intinerary',
            new_name='itinerary',
        ),
    ]
