# Generated by Django 6.0.4 on 2026-05-15 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='travel.travel'),
        ),
        migrations.AddField(
            model_name='monument',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travel'),
        ),
        migrations.AddField(
            model_name='visita',
            name='monument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.monument'),
        ),
        migrations.AddField(
            model_name='visita',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
