# Generated by Django 6.0.4 on 2026-05-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='valitation',
            new_name='validation',
        ),
    ]
