# Generated by Django 6.0.4 on 2026-05-05 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_intinerary_rute_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('itinerary', models.TextField()),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='travel.travel')),
            ],
        ),
        migrations.DeleteModel(
            name='Rute',
        ),
    ]
