# Generated by Django 6.0.4 on 2026-05-01 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_codigo_amigo_user_foto_perfil_amistad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogroDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogroDesbloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.logrodefinicion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_desbloqueados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'logro')},
            },
        ),
        migrations.DeleteModel(
            name='Logro',
        ),
    ]
